# Generated by Django 5.2 on 2025-04-22 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('ussd', 'USSD')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Phone Request',
                'verbose_name_plural': 'Phone Requests',
            },
        ),
        migrations.DeleteModel(
            name='PhoneRequest',
        ),
    ]
