# Generated by Django 5.2 on 2025-04-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_userprofile_delete_phonerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uuid',
        ),
    ]
