# Generated by Django 5.2 on 2025-04-23 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_userprofile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='captcha/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.userprofile')),
            ],
        ),
    ]
