# Generated by Django 5.2 on 2025-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_captchaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='second_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
